Repository o-cup/o-cup-web, pull requests merged in 2022-09, with the labels that each got.

#174 fix(173): 특전 빈 배열 입력되는 버그 수정
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/search/index.ts
  src/components/detail/GoodsInfo.tsx
  src/components/detail/goodsItems/FcfsGoodsListItem.tsx
  src/components/request/Goods/GoodsInput.tsx
  src/components/request/LuckyDraw/LuckyDrawInput.tsx
  src/components/request/PreviewContent.tsx
  src/components/request/requestApi.ts
  src/components/search/DistrictSelector.tsx
  src/components/search/Event.tsx
  src/components/search/Result.tsx
  src/components/search/SearchModal.tsx
  src/components/search/styles/districtSelectorStyle.ts
  src/hooks/index.ts
  src/hooks/useRegcodes.ts
  src/pages/Search.tsx
  src/shared/constants.ts
  src/shared/utils/dateHandlers.ts
  src/state/atoms.ts
  src/types.ts
Labels: bug

#179 feat(178): 뒤로가기 커서 영역 정상화
  src/shared/components/Icon/IconStyle.ts
  src/shared/components/layout/header/headerStyle.ts
Labels: fix

#184 feat(182): 이벤트데이 표시
  src/components/search/Event.tsx
  src/components/search/styles/eventStyle.ts
Labels: feature

#187 fix(186): 상세 페이지 뒤로가기 아이콘 표시
  src/shared/components/layout/header/index.tsx
Labels: fix

#190 fix(189): 신청페이지, 상세페이지 버그 수정
  package-lock.json
  src/components/detail/EventMain.tsx
  src/components/detail/goodsItems/LuckyGoodsListItem.tsx
  src/components/detail/styles/eventMainStyle.ts
  src/components/detail/styles/goodsInfoStyle.ts
  src/components/request/Artist/ArtistInput.tsx
  src/components/request/DateRange/DateRangeInput.tsx
  src/components/request/Entry.tsx
  src/components/request/FcfsGoods/FcfsGoodsInput.tsx
  src/components/request/FcfsGoods/fcfsGoodsInputStyle.ts
  src/components/request/LuckyDraw/LuckyDrawInput.tsx
  src/components/request/LuckyDraw/luckyInputStyle.ts
  src/components/request/Modals/AlertModal.tsx
  src/components/request/Modals/ConfirmModal.tsx
  src/components/request/Modals/SubmitModal.tsx
  src/components/request/Place/PlaceInput.tsx
  src/components/request/Poster/posterUploadStyle.ts
  src/components/request/PreviewContent.tsx
  src/components/request/requestApi.ts
  src/components/request/styles/requestStyle.ts
  src/components/request/units/BasicInput.tsx
  src/components/request/units/basicInputStyle.ts
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/Request.tsx
  src/shared/components/Modal/index.tsx
  src/shared/components/Modal/modalStyle.ts
  src/types.ts
Labels: fix

#196 feat(177): 검색 결과 지역 검색 필터링 적용
  public/images/icons/reset.png
  src/App.tsx
  src/apis/search/index.ts
  src/components/request/Entry.tsx
  src/components/request/Modals/AlertModal.tsx
  src/components/request/Modals/ConfirmModal.tsx
  src/components/request/Modals/SubmitModal.tsx
  src/components/request/styles/requestStyle.ts
  src/components/search/DistrictSelector.tsx
  src/components/search/Event.tsx
  src/components/search/Result.tsx
  src/components/search/SearchModal.tsx
  src/components/search/data.ts
  src/components/search/divisions.ts
  src/components/search/styles/districtSelectorStyle.ts
  src/components/search/styles/eventStyle.ts
  src/components/search/styles/searchStyle.ts
  src/hooks/useRegcodes.ts
  src/pages/Search.tsx
  src/shared/components/BiasProfile/index.tsx
  src/shared/components/Icon/IconStyle.ts
  src/shared/components/Modal/index.tsx
  src/shared/components/Modal/modalStyle.ts
Labels: feature

#199 feat(198): 메인 로고 클릭 시 최상단으로 이동
  src/shared/components/layout/header/index.tsx
Labels: feature

#212 feat(211): 검색 결과 화면에서 뒤로가기 시 검색 입력 페이지로 이동
  src/pages/Search.tsx
  src/shared/components/layout/header/index.tsx
  src/shared/components/layout/index.tsx
Labels: feature

#225 feat(221): 구글 애널리틱스 설정
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Wrapper.tsx
  src/hooks/useAnalytics.ts
  src/index.tsx
Labels: feature
