Repository o-cup/o-cup-web, pull requests merged in 2022-08, with the labels that each got.

#35 feat(26): 무한 스크롤 구현
  package-lock.json
  package.json
  src/apis/index.ts
  src/components/EventList/index.tsx
  src/components/EventsNearHere/index.tsx
  src/pages/Detail.tsx
  src/shared/constants.ts
Labels: feature

#36 feat(28): theming 구현, 레이아웃 max-width 변경
  src/App.tsx
  src/components/Filter/BottomSheet/CustomBottomSheet.tsx
  src/components/Filter/BottomSheet/DistrictSelector.tsx
  src/components/Filter/BottomSheet/data.ts
  src/components/Filter/BottomSheet/react-spring-bottom-sheet.css
  src/components/Filter/index.tsx
  src/styles/districtSelectorStyle.ts
  src/styles/eventListStyle.ts
  src/styles/eventMainStyle.ts
  src/styles/eventNearHereStyle.ts
  src/styles/filterStyle.ts
  src/styles/gloabalStyle.ts
  src/styles/goodsInfoStyle.ts
  src/styles/layoutStyle.ts
  src/styles/locationStyle.ts
  src/styles/theme.ts
  src/styles/twitterInfoStyle.ts
Labels: refactor

#37 feat(20): 인물 테이블 생성 및 연동, recoil 전역 state 작성, 월별 생일 프로필 표시 구현
  package-lock.json
  src/apis/index.ts
  src/components/Filter/Bias.tsx
  src/components/Filter/BiasList.tsx
  src/components/header/DateSelector.tsx
  src/state/atoms.ts
  src/styles/filterStyle.ts
  src/types.ts
Labels: feature

#39 feat(38): 특전 자세히보기 링크 추가
  src/components/GoodsInfo/index.tsx
  src/pages/Admin.tsx
  src/pages/Detail.tsx
  src/styles/goodsInfoStyle.ts
  src/types.ts
Labels: feature

#40 fix(26): 무한 스크롤 중복 데이터 버그 수정
  src/components/EventList/index.tsx
Labels: bug

#42 fix(41): 상세페이지 데이터 fetch 버그 수정
  src/apis/index.ts
  src/pages/Detail.tsx
Labels: bug

#46 feat(27) : 장소 full text search 구현
  src/apis/index.ts
  src/components/EventList/index.tsx
  src/components/Filter/SearchInput.tsx
  src/state/atoms.ts
  src/types.ts
Labels: feature

#47 fix(45): 사파리 모바일 웹에서 아이콘 및 텍스트 하늘색으로 표시되는 버그 수정
  src/styles/filterStyle.ts
  src/styles/gloabalStyle.ts
  src/styles/goodsInfoStyle.ts
Labels: fix

#49 feat(48): 검색 input 높이 수정, 데스크탑 이벤트 리스트 스타일 버그 수정
  src/styles/eventListStyle.ts
  src/styles/filterStyle.ts
Labels: bug

#51 fix(50): globalStyle 수정
  src/styles/gloabalStyle.ts
Labels: bug

#55 feat(54): 날짜 변환 dateHandlers.ts 추가, 회의 내용 반영
  src/components/EventList/EventListItem.tsx
  src/components/Filter/BiasList.tsx
  src/components/header/DateSelector.tsx
  src/pages/Detail.tsx
  src/shared/dateHandlers.ts
  src/state/atoms.ts
  src/styles/detailStyle.ts
  src/styles/eventListStyle.ts
  src/styles/layoutStyle.ts
Labels: feature

#53 feat(27): 인물, 장소, 주최자, 지역 데이터 필터링하여 검색 결과 노출
  src/apis/index.ts
Labels: feature

#75 feat(67): Footer 아이콘 영역 숨김
  src/styles/layoutStyle.ts
Labels: feature

#76 feat(70): 아이콘 fontawesome으로 통일
  src/components/EventList/EventListItem.tsx
  src/components/EventMain/index.tsx
  src/components/Filter/SearchInput.tsx
  src/components/Filter/index.tsx
  src/styles/eventListStyle.ts
  src/styles/eventMainStyle.ts
  src/styles/filterStyle.ts
Labels: style

#80 feat(58): 이벤트 쿼리 랜덤 순서 적용
  src/apis/index.ts
Labels: feature

#82 feat(57, 79): 인물 필터 구현
  src/components/EventList/index.tsx
  src/components/Filter/Bias.tsx
  src/components/Filter/BiasList.tsx
  src/components/header/DateSelector.tsx
  src/state/atoms.ts
  src/types.ts
Labels: feature

#83 feat(81): 인물 id로 테이블 쿼리, 칩 공통 컴포넌트 작성
  src/apis/index.ts
  src/components/EventList/EventListItem.tsx
  src/components/EventList/index.tsx
  src/components/EventMain/index.tsx
  src/components/EventsNearHere/index.tsx
  src/pages/Detail.tsx
  src/shared/components/BiasChip/BiasChip.tsx
  src/shared/components/BiasChip/BiasChipStyle.ts
  src/styles/eventListStyle.ts
  src/styles/eventMainStyle.ts
  src/types.ts
Labels: feature

#85 fix(84): eventMainStyle.ts 버그 수정
  src/styles/eventMainStyle.ts
Labels: bug

#91 fix(90): BiasChip 두명 이상인 경우 생략표시
  src/components/detail/EventMain.tsx
  src/components/main/EventListItem.tsx
  src/shared/components/BiasChip/biasChipStyle.ts
  src/shared/components/BiasChip/index.tsx
Labels: bug

#99 feat(73): Request 생성 및 BasicInput, Button 컴포넌트 작성
  public/images/icons/plus-circle.png
  public/images/logo_primary.png
  src/App.tsx
  src/components/request/BasicInput.tsx
  src/components/request/Entry.tsx
  src/components/request/Preview.tsx
  src/components/request/styles/basicInputStyle.ts
  src/components/request/styles/requestStyle.ts
  src/pages/Request.tsx
  src/shared/components/Button/buttonStyle.ts
  src/shared/components/Button/index.tsx
  src/shared/components/Icon/IconStyle.ts
  src/shared/components/Icon/Icons.tsx
  src/shared/components/layout/header/index.tsx
Labels: feature

#102 feat(73): 인풋 삭제 구현
  public/images/icons/delete.png
  src/components/request/BasicInput.tsx
  src/components/request/Entry.tsx
  src/components/request/styles/basicInputStyle.ts
Labels: feature

#112 feat(103): 포스터 업로드 및 삭제 구현
  public/images/icons/delete-circle_white.png
  src/components/request/BasicInput.tsx
  src/components/request/Entry.tsx
  src/components/request/PosterUploader.tsx
  src/components/request/styles/basicInputStyle.ts
  src/components/request/styles/posterUploadStyle.ts
  src/components/request/styles/requestStyle.ts
  src/pages/Request.tsx
  src/shared/components/Icon/IconStyle.ts
  src/shared/components/Icon/Icons.tsx
Labels: feature

#115 feat(98): 가까운 연관 이벤트 가로 전체 너비 차지하도록 수정
  src/components/detail/styles/detailStyle.ts
  src/components/detail/styles/eventMainStyle.ts
  src/components/detail/styles/eventNearHereStyle.ts
  src/pages/Detail.tsx
Labels: feature

#118 feat(113): Header 컴포넌트에 title 추가
  src/pages/Main.tsx
  src/pages/Request.tsx
  src/shared/components/layout/header/index.tsx
  src/shared/components/layout/index.tsx
  src/shared/components/layout/styles/layoutStyle.ts
Labels: feature

#131 feat(68): 검색 페이지 구현
  .github/pull_request_template.md
  public/images/icons/sort.png
  src/App.tsx
  src/apis/index.ts
  src/components/main/Bias.tsx
  src/components/main/SearchInput.tsx
  src/components/main/index.ts
  src/components/main/styles/mainStyle.ts
  src/components/request/Entry.tsx
  src/components/search/MonthSelector.tsx
  src/components/search/SearchInput.tsx
  src/components/search/styles/monthSelectorStyle.ts
  src/components/search/styles/searchInputStyle.ts
  src/components/search/styles/searchStyle.ts
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/shared/components/BiasProfile/biasProfileStyle.ts
  src/shared/components/BiasProfile/index.tsx
  src/shared/components/Icon/IconStyle.ts
  src/shared/components/Sort/index.tsx
  src/shared/components/Sort/sortStyle.ts
  src/shared/components/ToggleButton/index.tsx
  src/shared/utils/dateHandlers.ts
  src/styles/theme.ts
Labels: feature

#138 feat(69): 검색 결과 페이지 구현
  package-lock.json
  public/images/icons/arrow-left.png
  public/images/icons/filter.png
  public/images/icons/place.png
  public/images/icons/share.png
  src/apis/index.ts
  src/components/detail/EventMain.tsx
  src/components/main/BottomSheet/CustomBottomSheet.tsx
  src/components/main/BottomSheet/react-spring-bottom-sheet.css
  src/components/main/index.ts
  src/components/main/styles/districtSelectorStyle.ts
  src/components/request/DateRangeInput.tsx
  src/components/request/Entry.tsx
  src/components/request/SearchInput.tsx
  src/components/request/styles/modalStyle.ts
  src/components/search/DistrictSelector.tsx
  src/components/search/Event.tsx
  src/components/search/Result.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchModal.tsx
  src/components/search/data.ts
  src/components/search/index.ts
  src/components/search/styles/districtSelectorStyle.ts
  src/components/search/styles/eventStyle.ts
  src/components/search/styles/monthSelectorStyle.ts
  src/components/search/styles/resultStyle.ts
  src/components/search/styles/searchInputStyle.ts
  src/components/search/styles/searchStyle.ts
  src/pages/Admin.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/Request.tsx
  src/pages/Search.tsx
  src/shared/components/BiasChip/biasChipStyle.ts
  src/shared/components/BiasChip/index.tsx
  src/shared/components/BottomSheet/index.tsx
  src/shared/components/Calendar/calendarStyle.ts
  src/shared/components/Calendar/index.tsx
  src/shared/components/FilterIcon/filterIconStyle.ts
  src/shared/components/FilterIcon/index.tsx
  src/shared/components/Icon/IconStyle.ts
  src/shared/components/Modal/index.tsx
  src/shared/components/Modal/modalStyle.ts
  src/shared/components/Sort/index.tsx
  src/shared/components/SortIcon/index.tsx
  src/shared/components/SortIcon/sortIconStyle.ts
  src/shared/components/index.ts
  src/shared/components/layout/header/HeaderCalendar/index.tsx
  src/shared/components/layout/header/headerStyle.ts
  src/shared/components/layout/header/index.tsx
  src/shared/components/layout/index.tsx
  src/shared/components/layout/styles/layoutStyle.ts
  src/state/recoilUtils.ts
  src/styles/gloabalStyle.ts
Labels: feature

#144 fix(143): 연관이벤트 버그 수정
  src/components/detail/EventNearHere.tsx
Labels: bug, fix

#146 feat(66): 지역 데이터 업데이트, 모달 오픈 시 배경 스크롤 제한 및 모달 위치 개선
  src/components/request/styles/modalStyle.ts
  src/components/search/data.ts
  src/shared/components/Modal/index.tsx
  src/styles/gloabalStyle.ts
  src/styles/theme.ts
Labels: feature

#155 feat(148): 검색 결과 페이지 지역, 날짜 칩 구현
  public/images/icons/delete-gray.png
  src/components/search/DistrictSelector.tsx
  src/components/search/Result.tsx
  src/components/search/SearchModal.tsx
  src/components/search/styles/districtSelectorStyle.ts
  src/components/search/styles/resultStyle.ts
  src/components/search/types.ts
  src/shared/components/Button/buttonStyle.ts
  src/shared/components/Button/index.tsx
  src/shared/components/Chip/chipStyle.ts
  src/shared/components/Chip/index.tsx
  src/shared/components/Icon/IconStyle.ts
  src/state/atoms.ts
  src/state/index.ts
  src/types.ts
Labels: feature
